SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[selectAllInstructorCourses]
AS
BEGIN TRY
SELECT  * FROM  Instructors_Courses 
END TRY
BEGIN CATCH
 SELECT 'ERROR! in Selection Operation'
END CATCH
GO