SET IDENTITY_INSERT dbo.Topics ON
GO
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (1, 'tags', 1);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (2, 'links', 1);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (3, 'imgs', 1);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (4, 'table', 1);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (5, 'forms', 1);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (6, 'lists', 1);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (7, 'colors', 1);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (8, 'styles', 1);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (9, 'selectors', 2);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (10, 'colors', 2);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (11, 'bsckgrounds', 2);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (12, 'comments', 2);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (13, 'borders', 2);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (14, 'box model', 2);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (15, 'icons', 2);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (16, 'overflow', 2);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (17, 'displsying', 2);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (18, 'variables', 3);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (19, 'let', 3);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (20, 'const', 3);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (21, 'var', 3);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (22, 'functions', 3);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (23, 'arrayas', 3);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (24, 'strings', 3);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (25, 'dates', 3);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (26, 'math', 3);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (27, 'random', 3);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (28, 'looping', 3);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (29, 'mapping', 3);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (30, 'Erros', 3);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (31, 'arrow functions', 3);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (32, 'flexbox', 4);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (33, 'grid', 4);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (34, 'templstes', 4);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (35, 'medisquery', 4);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (36, 'viewport', 4);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (37, 'imsges ', 4);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (38, 'frameworks', 4);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (39, 'variables', 5);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (40, 'datatypes', 5);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (41, 'operstors', 5);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (42, 'math', 5);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (43, 'strings', 5);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (44, 'array', 5);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (45, 'looping', 5);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (46, 'casting', 5);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (47, 'switch', 5);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (48, 'tree', 6);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (49, 'syntax', 6);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (50, 'elements', 6);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (51, 'attrs', 6);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (52, 'parser', 6);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (53, 'DOM', 6);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (54, 'schema', 6);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (55, 'validators', 6);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (56, 'display', 6);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (57, 'functiond', 7);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (58, 'arrow functions', 7);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (59, 'arrays', 7);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (60, 'seq diagram', 8);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (61, 'class diagram', 8);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (62, 'usecase diagram', 8);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (63, 'stored proc', 9);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (64, 'functs', 9);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (65, 'ERD', 9);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (66, 'Routes', 10);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (67, 'models', 10);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (68, 'schemas', 10);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (69, 'schemas', 11);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (70, 'crud', 11);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (71, 'initialization', 11);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (72, 'authurization', 11);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (73, 'xyz', 12);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (74, 'abc', 12);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (75, 'DML', 12);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (76, 'PROC', 13);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (77, 'FUNC', 13);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (78, 'CURSOR', 13);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (79, 'VARS', 14);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (80, 'Views', 14);
INSERT dbo.Topics(topic_id, topic_name, curs_id) VALUES (81, 'Storeds', 14);
GO
SET IDENTITY_INSERT dbo.Topics OFF
GO